### ISSUE TITLE
multiplayer

### ISSUE THREAD

**Issue by anherukun** [MinicraftPlus/minicraft-plus-online#17]
Error connection to suggested server from sever list

**Comment by anherukun** [comment]
Yep, already download the latest version from repository... im using this hostname: **mc.smp.com** from the server list, instead a IP address, I am right? or im need to use IP address only?

**Comment by El-Virus** [comment]
Well, @anherukun, that's a community server, which happens to be offline. We ourselves only provide the authentication server.
Minicraft online does however have the capability to resolve DNs.

**Comment by El-Virus** [comment]
Closed due to inactivity.
